### ISSUE TITLE
Ubuntu 22.04.4 LTS 通过星火商店安装的 Lyricify 无法启动

### ISSUE THREAD

**Issue by pxyWaterMoon** [Lyricify/Lyricify-on-Wine#1]
我利用星火商店进行安装。在安装完成后点击图标，第一次的时候会弹出来 “Lyricify 配置”一会儿后消失然后就没有其他反应，之后再点击图标就没有其他的反应了。请问你们有遇到这种情况吗？
系统：Ubuntu 22.04.4 LTS

**Comment by fred913** [comment]
请提供以下信息，以方便我们定位、修复问题。
1. 你所说的“Lyricify 配置”窗口截图，进度条无所谓；
2. 系统neofetch截图，或手动整理提供各项系统信息
3. 根据仓库readme手动安装deb包并运行的全流程日志。

**Comment by pxyWaterMoon** [comment]
我是通过星火商店安装的，安装过程就是在商店页面点击下载
![截图 2024-05-10 16-05-57](https://github.com/Lyricify/Lyricify-on-Wine/assets/89518054/6ab7754e-2417-4092-8e83-7f9b586b1d57)

安装完成后它会弹出通知
![截图 2024-05-10 16-07-35](https://github.com/Lyricify/Lyricify-on-Wine/assets/89518054/9a04e77a-e239-47da-b952-74bacb49fdf2)


并且在菜单栏会有图标
![截图 2024-05-10 16-09-02](https://github.com/Lyricify/Lyricify-on-Wine/assets/89518054/11c16975-3ea0-4fa3-88e3-d1a4cd578d7d)


点击图标后它会弹出一个初始化的弹窗：
![截图 2024-05-10 16-07-50](https://github.com/Lyricify/Lyricify-on-Wine/assets/89518054/1a1e359c-c4fd-451c-b871-1ac569d0115f)
并且进度条有点像是在加载那种来回走的而不是从0开始逐渐增加到100那种。一段时间之后（大约半分钟左右？）这个弹窗就消失了，并且没有其他窗口出现。然后，我再次从菜单栏点击 lyricify 的图标就没有任何反应。

neofetch 如下：
![截图 2024-05-10 16-17-10](https://github.com/Lyricify/Lyricify-on-Wine/assets/89518054/f87cd01a-dde9-4fcc-a046-174245ae73e6)

**Comment by fred913** [comment]
感谢反馈，我尝试在类似环境中复现一下，将尽快回复。

**Comment by fred913** [comment]
@pxyWaterMoon 另：您是否尝试过参考仓库readme，手动安装deb包？如果没有，能否麻烦尝试一下？

**Comment by Jerry-Z07** [comment]
在ubuntu 24.04遇到相同问题，表现完全相同，附neofetch信息如下
OS: Ubuntu 24.04 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 6.8.0-31-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 30 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2122 (dpkg), 12 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.2.21 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1366x768 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 46.0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i3-6100 (4) @ 3.700GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GTX 960 
    .ossssssssssssssssssdMMMNysssso.       Memory: 2186MiB / 11913MiB 
界面环境是wayland,显卡驱动为nouveau版本

**Comment by fred913** [comment]
> 在ubuntu 24.04遇到相同问题，表现完全相同，附neofetch信息如下
> OS: Ubuntu 24.04 LTS x86_64 
>     .ossssssssssssssssssdMMMNysssso.       Kernel: 6.8.0-31-generic 
>    /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 30 mins 
>   +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2122 (dpkg), 12 (snap) 
>  /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.2.21 
> .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1366x768 
> +sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 46.0 
> ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
> ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
> +sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru [GTK2/3] 
> .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3] 
>  /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
>   +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i3-6100 (4) @ 3.700GHz 
>    /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GTX 960 
>     .ossssssssssssssssssdMMMNysssso.       Memory: 2186MiB / 11913MiB 
> 界面环境是wayland,显卡驱动为nouveau版本

@enKl03B 是否尝试过参考仓库readme，手动安装deb包？如果没有，能否麻烦尝试一下？

**Comment by fred913** [comment]
> 在ubuntu 24.04遇到相同问题，表现完全相同，附neofetch信息如下
> OS: Ubuntu 24.04 LTS x86_64 
>     .ossssssssssssssssssdMMMNysssso.       Kernel: 6.8.0-31-generic 
>    /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 30 mins 
>   +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2122 (dpkg), 12 (snap) 
>  /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.2.21 
> .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1366x768 
> +sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 46.0 
> ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
> ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
> +sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru [GTK2/3] 
> .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3] 
>  /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
>   +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i3-6100 (4) @ 3.700GHz 
>    /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GTX 960 
>     .ossssssssssssssssssdMMMNysssso.       Memory: 2186MiB / 11913MiB 
> 界面环境是wayland,显卡驱动为nouveau版本

@enKl03B 是否尝试过参考仓库readme，手动安装deb包？如果没有，能否麻烦尝试一下？

**Comment by Jerry-Z07** [comment]
> > 在ubuntu 24.04遇到相同问题，表现完全相同，附neofetch信息如下
> > OS: Ubuntu 24.04 LTS x86_64
> > .ossssssssssssssssssdMMMNysssso.       Kernel: 6.8.0-31-generic
> > /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 30 mins
> > +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2122 (dpkg), 12 (snap)
> > /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.2.21
> > .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1366x768
> > +sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 46.0
> > ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter
> > ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita
> > +sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru [GTK2/3]
> > .ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru [GTK2/3]
> > /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal
> > +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i3-6100 (4) @ 3.700GHz
> > /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA GeForce GTX 960
> > .ossssssssssssssssssdMMMNysssso.       Memory: 2186MiB / 11913MiB
> > 界面环境是wayland,显卡驱动为nouveau版本
> 
> @enKl03B 是否尝试过参考仓库readme，手动安装deb包？如果没有，能否麻烦尝试一下？

是的，已经尝试过了，问题依旧

**Comment by fred913** [comment]
了解，我会尽快测试并尝试复现

enKl03B ***@***.***> 于2024年5月19日周日 14:43写道：

**Comment by yuzh496** [comment]
我是linuxmint22.3（基于ubuntu24.04），星火商店安装后运行没反应，然后用桌面启动图标里的命令行"/opt/apps/com.wxriw.lyricify4/files/run.sh" --uri运行，提示如下。

ThinkBook-16-G4-IAP:~$ "/opt/apps/com.wxriw.lyricify4/files/run.sh" --uri 
cat: /opt/apps/com.wxriw.lyricify4/files/wine_archive.md5sum: 没有那个文件或目录
/opt/spark-dwine-helper
Loading transhell from /opt/spark-dwine-helper/transhell/spark_run_v4.sh_en_US.transhell ...
Loading transhell from /opt/spark-dwine-helper/transhell/spark_run_v4.sh_zh_CN.transhell ...
-----------------------------------------------------------------------------
[DEBUG]: Using p7zip-legacy as unpacker
[DEBUG]: Run Lyricify 4.2.28.240502-release-wpack240503.01 c:/Program Files/Lyricify 4/Lyricify for Spotify.exe --uri
[DEBUG]: run Lyricify progress pid 
/home/yuzh/Desktop 不是目录，不能创建Desktop软连接
/home/yuzh/Downloads 不是目录，不能创建Downloads软连接
env: "/home/yuzh/.deepinwine/wine-staging-wow64-9.7-debian10-amd64/bin/wine64": 没有那个文件或目录
[DEBUG]: CallApp Lyricify arg count 1: c:/Program Files/Lyricify 4/Lyricify for Spotify.exe
/opt/spark-dwine-helper/spark_run_v4_app_configs/Lyricify.sh 文件不存在，执行通用启动
Don't use public dir
2026年 01月 27日 星期二 20:58:35 CST:kill Lyricify block
2026年 01月 27日 星期二 20:58:35 CST:tag bottle: /home/yuzh/.deepinwine/Lyricify
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.deepin.dde.TrayManager': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark-dwine-helper/spark_get_tray_window", line 22, in <module>
    get_tray_window()
  File "/opt/spark-dwine-helper/spark_get_tray_window", line 11, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 228, in partial_apport_excepthook
    return apport_excepthook(binary, exc_type, exc_obj, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 144, in apport_excepthook
    os.open(pr_filename, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), "wb"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/crash/_opt_spark-dwine-helper_spark_get_tray_window.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 173, in activate_name_owner
    return self.get_name_owner(bus_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 348, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'com.deepin.dde.TrayManager': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/spark-dwine-helper/spark_get_tray_window", line 22, in <module>
    get_tray_window()
  File "/opt/spark-dwine-helper/spark_get_tray_window", line 11, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 237, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 178, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 273, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
2026年 01月 27日 星期二 20:58:38 CST:active bottles: 
2026年 01月 27日 星期二 20:58:38 CST:try to kill /home/yuzh/.deepinwine/Lyricify
/opt/spark-dwine-helper/spark_kill.sh: 行 60: /proc/387905/environ: 没有那个文件或目录
cat: /proc/387905/maps: 没有那个文件或目录
cat: /proc/387905/cmdline: 没有那个文件或目录
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/387905/maps: 没有那个文件或目录
cat: /proc/939/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/939/maps: 权限不够
cat: /proc/943/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/943/maps: 权限不够
cat: /proc/966/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/966/maps: 权限不够
cat: /proc/975/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/975/maps: 权限不够
cat: /proc/986/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/986/maps: 权限不够
cat: /proc/1134/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/1134/maps: 权限不够
cat: /proc/1213/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/1213/maps: 权限不够
cat: /proc/1246/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/1246/maps: 权限不够
cat: /proc/1389/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/1389/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/153133/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/153133/maps: 权限不够
cat: /proc/343702/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/343702/maps: 权限不够
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/387930/maps: 没有那个文件或目录
cat: /proc/387930/cmdline: 没有那个文件或目录
xargs: 警告：选项 --max-lines 和 --replace/-I/-i 互斥，已忽略之前的 --max-lines 值
cat: /proc/387930/maps: 没有那个文件或目录
yuzh      388879  387600  0 20:58 pts/1    00:00:00 grep -E yuzh.*exe.*<defunct>
/home/yuzh/.deepinwine/Lyricify/drive_c/Program Files/Lyricify 4
env: "/home/yuzh/.deepinwine/wine-staging-wow64-9.7-debian10-amd64/bin/wine64": 没有那个文件或目录
[DEBUG]: Starting process c:/Program Files/Lyricify 4/Lyricify for Spotify.exe ...
检测到的缩放倍数为:1.25
Scale is 1.25
用/home/yuzh/.deepinwine/wine-staging-wow64-9.7-debian10-amd64/bin/wine64执行指令
指令为
env WINEPREFIX=/home/yuzh/.deepinwine/Lyricify /home/yuzh/.deepinwine/wine-staging-wow64-9.7-debian10-amd64/bin/wine64 reg ADD 'HKCU\Control Panel\Desktop' /v LogPixels /t REG_DWORD /d 120 /f
env: "/home/yuzh/.deepinwine/wine-staging-wow64-9.7-debian10-amd64/bin/wine64": 没有那个文件或目录
env: "/home/yuzh/.deepinwine/wine-staging-wow64-9.7-debian10-amd64/bin/wine64": 没有那个文件或目录


————————————————————————
<pre>neofetch
<b>             ...-:::::-...</b>                 <font color="#8AE234"><b>yuzh</b></font>@<font color="#8AE234"><b>ThinkBook-16-G4-IAP</b></font> 
<b>          .-MMMMMMMMMMMMMMM-.</b>              ----------------------------- 
<b>      .-MMMM</b><font color="#8AE234"><b>`..-:::::::-..`</b></font><b>MMMM-.</b>          <font color="#8AE234"><b>OS</b></font>: Linux Mint 22.3 x86_64 
<b>    .:MMMM</b><font color="#8AE234"><b>.:MMMMMMMMMMMMMMM:.</b></font><b>MMMM:.</b>        <font color="#8AE234"><b>Host</b></font>: 21CY ThinkBook 16 G4+ IAP 
<b>   -MMM</b><font color="#8AE234"><b>-M---MMMMMMMMMMMMMMMMMMM.</b></font><b>MMM-</b>       <font color="#8AE234"><b>Kernel</b></font>: 6.14.0-37-generic 
<b> `:MMM</b><font color="#8AE234"><b>:MM`  :MMMM:....::-...-MMMM:</b></font><b>MMM:`</b>    <font color="#8AE234"><b>Uptime</b></font>: 3 hours, 56 mins 
<b> :MMM</b><font color="#8AE234"><b>:MMM`  :MM:`  ``    ``  `:MMM:</b></font><b>MMM:</b>    <font color="#8AE234"><b>Packages</b></font>: 2480 (dpkg) 
<b>.MMM</b><font color="#8AE234"><b>.MMMM`  :MM.  -MM.  .MM-  `MMMM.</b></font><b>MMM.</b>   <font color="#8AE234"><b>Shell</b></font>: bash 5.2.21 
<b>:MMM</b><font color="#8AE234"><b>:MMMM`  :MM.  -MM-  .MM:  `MMMM-</b></font><b>MMM:</b>   <font color="#8AE234"><b>Resolution</b></font>: 2560x1600 
<b>:MMM</b><font color="#8AE234"><b>:MMMM`  :MM.  -MM-  .MM:  `MMMM:</b></font><b>MMM:</b>   <font color="#8AE234"><b>DE</b></font>: Cinnamon 6.6.6 
<b>:MMM</b><font color="#8AE234"><b>:MMMM`  :MM.  -MM-  .MM:  `MMMM-</b></font><b>MMM:</b>   <font color="#8AE234"><b>WM</b></font>: Mutter (Muffin) 
<b>.MMM</b><font color="#8AE234"><b>.MMMM`  :MM:--:MM:--:MM:  `MMMM.</b></font><b>MMM.</b>   <font color="#8AE234"><b>WM Theme</b></font>: Qogir-Light (Mint-Y) 
<b> :MMM</b><font color="#8AE234"><b>:MMM-  `-MMMMMMMMMMMM-`  -MMM-</b></font><b>MMM:</b>    <font color="#8AE234"><b>Theme</b></font>: Qogir-Light [GTK2/3] 
<b>  :MMM</b><font color="#8AE234"><b>:MMM:`                `:MMM:</b></font><b>MMM:</b>     <font color="#8AE234"><b>Icons</b></font>: Yaru-red-dark [GTK2/3] 
<b>   .MMM</b><font color="#8AE234"><b>.MMMM:--------------:MMMM.</b></font><b>MMM.</b>      <font color="#8AE234"><b>Terminal</b></font>: gnome-terminal 
<b>     &apos;-MMMM</b><font color="#8AE234"><b>.-MMMMMMMMMMMMMMM-.</b></font><b>MMMM-&apos;</b>       <font color="#8AE234"><b>CPU</b></font>: 12th Gen Intel i5-12500H (16) @ 4.500GHz 
<b>       &apos;.-MMMM</b><font color="#8AE234"><b>``--:::::--``</b></font><b>MMMM-.&apos;</b>         <font color="#8AE234"><b>GPU</b></font>: NVIDIA GeForce RTX 2050 
<b>            &apos;-MMMMMMMMMMMMM-&apos;</b>              <font color="#8AE234"><b>GPU</b></font>: Intel Alder Lake-P GT2 [Iris Xe Graphics] 
<b>               ``-:::::-``</b>                 <font color="#8AE234"><b>Memory</b></font>: 7091MiB / 15715MiB 

                                           <span style="background-color:#2E3436"><font color="#2E3436">   </font></span><span style="background-color:#CC0000"><font color="#CC0000">   </font></span><span style="background-color:#4E9A06"><font color="#4E9A06">   </font></span><span style="background-color:#C4A000"><font color="#C4A000">   </font></span><span style="background-color:#3465A4"><font color="#3465A4">   </font></span><span style="background-color:#75507B"><font color="#75507B">   </font></span><span style="background-color:#06989A"><font color="#06989A">   </font></span><span style="background-color:#D3D7CF"><font color="#D3D7CF">   </font></span>
                                           <span style="background-color:#555753"><font color="#555753">   </font></span><span style="background-color:#EF2929"><font color="#EF2929">   </font></span><span style="background-color:#8AE234"><font color="#8AE234">   </font></span><span style="background-color:#FCE94F"><font color="#FCE94F">   </font></span><span style="background-color:#729FCF"><font color="#729FCF">   </font></span><span style="background-color:#AD7FA8"><font color="#AD7FA8">   </font></span><span style="background-color:#34E2E2"><font color="#34E2E2">   </font></span><span style="background-color:#EEEEEC"><font color="#EEEEEC">   </font></span>
</pre>
